### ISSUE TITLE
Could not find jni.h

### ISSUE THREAD

**Issue by mymagicpower** [kherud/java-llama.cpp#10]
PS F:\LLM\java-llama.cpp\scripts> .\build.bat
-- Building for: Visual Studio 16 2019
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.22621.
-- The CXX compiler identification is MSVC 19.29.30148.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Java: D:/Program Files/Java/jdk-17/bin/java.exe (found version "17.0.8")
CMake Error at CMakeLists.txt:16 (message):
  Could not find jni.h

-- Configuring incomplete, errors occurred!

**Comment by mymagicpower** [comment]
Issue fixed after configure JAVA_HOME:
![1695263091932](https://github.com/kherud/java-llama.cpp/assets/37390155/2d163838-e3da-4d9f-b95a-b2a43e956277)

**Comment by kherud** [comment]
Oh sorry, I forgot to make that clear in the readme. Yes, `$JAVA_HOME` has to be set, since it contains the necessary JNI headers to compile the library.

**Comment by kherud** [comment]
I updated the readme with better instructions, including setting $JAVA_HOME. I'm closing this ticket for now.
