### ISSUE TITLE
version `GLIBCXX_3.4.29' not found

### ISSUE THREAD

**Issue by sc3sc3** [kherud/java-llama.cpp#19]
When using 
```
<dependency>
    <groupId>de.kherud</groupId>
    <artifactId>llama</artifactId>
    <version>2.2.1</version>
</dependency>
```
i get the following error
_Extracted 'libllama.so' to '/tmp/libllama.so'
/tmp/libllama.so: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /tmp/libllama.so)
Failed to load native library: /tmp/libllama.so. osinfo: Linux/x86_64_

I presume the maven jar is built with different c++ dependencies than i have available on my system ( ubuntu 20.04 )

I manage to build the project and concerning *.so files
but how can I make a jar out of it locally ?

Thanks for your time and project.
Regards

**Comment by sc3sc3** [comment]
> I also met the same problem when i run it on linux ![image](https://user-images.githubusercontent.com/67722928/276877899-2b45bf67-0e03-4d72-b337-eb15b981fc92.png)

what flavor/version of linux are you running ?

the official linux jar is built with ubuntu 22.04

**Comment by Solido** [comment]
It's not up to java llama to share C++ lib GLIBCXX.
Update your system to match required version.
