### ISSUE TITLE
multiple definition of `pthread_mutex_destroy'; first defined here

### ISSUE THREAD

**Issue by fucksmile** [kherud/java-llama.cpp#20]
Hello,
H:\mingw-w64\w64devkit-fortran-1.13.0\w64devkit\bin/ld.exe: h:/mingw-w64/w64devkit-fortran-1.13.0/w64devkit/bin/../lib/gcc/x86_64-w64-mingw32/11.3.0/../../../../x86_64-w64-mingw32/lib/../lib/libpthread.a(libwinpthread_la-mutex.o):mutex.c:(.text+0x2b9): multiple definition of `pthread_mutex_destroy'; src/main/cpp/llama.cpp/libllama.dll.a(libllama_dll_d000649.o):(.text+0x0): first defined here

H:\mingw-w64\w64devkit-fortran-1.13.0\w64devkit\bin/ld.exe: h:/mingw-w64/w64devkit-fortran-1.13.0/w64devkit/bin/../lib/gcc/x86_64-w64-mingw32/11.3.0/../../../../x86_64-w64-mingw32/lib/../lib/libpthread.a(libwinpthread_la-mutex.o):mutex.c:(.text+0x368): multiple definition of `pthread_mutex_init'; src/main/cpp/llama.cpp/libllama.dll.a(libllama_dll_d000650.o):(.text+0x0): first defined here

H:\mingw-w64\w64devkit-fortran-1.13.0\w64devkit\bin/ld.exe: h:/mingw-w64/w64devkit-fortran-1.13.0/w64devkit/bin/../lib/gcc/x86_64-w64-mingw32/11.3.0/../../../../x86_64-w64-mingw32/lib/../lib/libpthread.a(libwinpthread_la-thread.o):thread.c:(.text+0x10a6): multiple definition of `pthread_self'; src/main/cpp/llama.cpp/libllama.dll.a(libllama_dll_d000680.o):(.text+0x0): first defined here

collect2.exe: error: ld returned 1 exit status
make[2]: *** [CMakeFiles\jllama.dir\build.make:110: H:/aidata/java-llama.cpp/src/main/resources/de/kherud/llama/Windows/x86_64/libjllama.dll] Error 1
make[1]: *** [CMakeFiles\Makefile2:125: CMakeFiles/jllama.dir/all] Error 2
make: *** [Makefile:135: all] Error 2

H:\mydata\java-llama.cpp\build>g++ --version
g++ (GCC) 11.3.0

**Comment by kherud** [comment]
I'll close this issue for now. If you still have problems give version 3.0 a try and feel free to re-open the ticket otherwise.
