### ISSUE TITLE
not getting gpu acceleration on windows

### ISSUE THREAD

**Issue by siddhsql** [kherud/java-llama.cpp#43]
i am running version 2.2.1 of this library on a windows PC with [intel iris plus graphics 655](https://www.intel.com/content/www/us/en/support/products/197532/graphics/intel-iris-plus-graphics.html) and do not see the gpu being used. is this because the underlying `llama.cpp` does not support it or something else? is there something i can do to get gpu acceleration on windows?

**Comment by kherud** [comment]
Hi @siddhsql the pre-compiled libraries this Java package provides are CPU only. For GPU support, you have to compile llama.cpp yourself. Please refer to these instructions https://github.com/kherud/java-llama.cpp#setup-required

**Comment by siddhsql** [comment]
Hi Konstantin,

Thanks for your reply. I built a custom binary of llama.cpp that uses
CLBlast. I confirmed that when I run llama.cpp directly using the main.exe
program, I get GPU acceleration but I do not get any GPU acceleration when
using java-llama.cpp. I have set de.kherud.llama.lib.path to the location
where I have jllama.dll and llama.dll. is there something I am missing?
Can you provide more instructions?

**Comment by siddhsql** [comment]
nevermind. i fixed it.
