### ISSUE TITLE
[Suggestion] Keep loaded model separate from context

### ISSUE THREAD

**Issue by tiguchi** [kherud/java-llama.cpp#5]
I would like to use the shared library for serving an LLM through an inference endpoint that can serve multiple requests with varying temperature and max token settings. At the moment the `LlamaModel` seems to be merged with the context, and the only way to set the temperature or max tokens again would be by closing / freeing the model and loading it again with the correct configuration.

I would like to keep the model loaded though, and allocate separate contexts with different configurations per incoming completion request. Is that possible using the llamap.cpp API, and would you consider making changes to java-llama.cpp for that?

**Comment by kherud** [comment]
Yes, I think that would be a nice improvement. One thing I am working on anyway is to separate model specific and inference specific parameters. Currently, these can only be changed when constructing a `LlamaModel`.
I was thinking to overload `LLamaModel#generate(String)` with `LLamaModel#generate(String, InferenceParameters)`. This way I can also enable to pass a context.

**Comment by kherud** [comment]
The requirements of this issue are implemented since a few versions, so I'll close this ticket. Let me know if you still have questions.
