### ISSUE TITLE
Update to a newer version of llama.cpp

### ISSUE THREAD

**Issue by RFYoung** [kherud/java-llama.cpp#51]
Hello,

Thanks for your amazing project!

As llama.cpp keeps updating, I am wondering if it possible to update llama.cpp used in this project. 

One of the reasons for this is that llama.cpp now supports some new model structures (like Qwen 1.5), which are not implemented in older versions.

To directly compile on a newer version would fail. I think this might be because there are some refactors in llama.cpp.  I am not sure this would be easy work.

Thanks!

**Comment by kherud** [comment]
Hey @RFYoung absolutely this is possible. I've been quite busy the last few weeks but I have the time to have a look this week.

**Comment by kherud** [comment]
I'm happy to announce version 3.0 https://github.com/kherud/java-llama.cpp/releases/tag/v3.0.0 let me know if you miss anything
