### ISSUE TITLE
llama_new_context_with_model: ggml_metal_init() failed

### ISSUE THREAD

**Issue by mymagicpower** [kherud/java-llama.cpp#6]
Model:
https://huggingface.co/TheBloke/Llama-2-7B-GGUF/resolve/main/llama-2-7b.Q4_0.gguf

Error log:
..................................................................................................
llama_new_context_with_model: kv self size  =  256.00 MB
ggml_metal_init: allocating
ggml_metal_init: found device: Intel(R) Iris(TM) Plus Graphics 655
ggml_metal_init: picking default device: Intel(R) Iris(TM) Plus Graphics 655
ggml_metal_init: loading '/Users/calvin/aias_projects/java-llama.cpp/target/classes/ggml-metal.metal'
ggml_metal_init: error: Error Domain=MTLLibraryErrorDomain Code=3 "program_source:41:9: error: invalid type 'const constant int64_t &' (aka 'const constant long &') for buffer declaration
        constant   int64_t & nb,
        ^~~~~~~~~~~~~~~~~~~~~~~
program_source:41:20: note: type 'int64_t' (aka 'long') cannot be used in buffer pointee type
        constant   int64_t & nb,
                   ^
program_source:60:9: error: invalid type 'const constant int64_t &' (aka 'const constant long &') for buffer declaration
        constant    int64_t & nb,
        ^~~~~~~~~~~~~~~~~~~~~~~~
program_source:60:21: note: type 'int64_t' (aka 'long') cannot be used in buffer pointee type
        constant    int64_t & nb,
                    ^
program_source:107:9: error: invalid type 'const constant int64_t &' (aka 'const constant long &') for buffer declaration
        constant   int64_t & ne00,
.......
.......
.......
.......
.......
.......

program_source:2030:28: error: invalid type 'const constant int64_t &' (aka 'const constant long &') for buffer declaration
                           constant    int64_t & ne1,
                           ^~~~~~~~~~~~~~~~~~~~~~~~~
program_source:2030:40: note: type 'int64_t' (aka 'long') cannot be used in buffer pointee type
                           constant    int64_t & ne1,
                                       ^
}
llama_new_context_with_model: ggml_metal_init() failed

**Comment by warner1235** [comment]
I had a similar problem in the past.
try Q5_K_M instead of Q4.

**Comment by kherud** [comment]
This looks to me like something goes wrong on the C++ side. Does this also happen when for example using the Python API?

**Comment by mymagicpower** [comment]
issue fixed. (My laptop is MacPro intel x86, not M1 or M2)
 So -DLLAMA_METAL=ON should be -DLLAMA_METAL=OFF.
------------------------------------------------------------
cmake .. -DBUILD_SHARED_LIBS=ON -DLLAMA_METAL=OFF
