### ISSUE TITLE
Interrupting inference?

### ISSUE THREAD

**Issue by jrtp** [kherud/java-llama.cpp#62]
Nice work :) 
I did not find a way to cleanly interrupt inference, could only supress output from the iterable loop. Is this somehow possible?

**Comment by kherud** [comment]
Hey @jrtp thanks for the issue, this was indeed not possible. However, it can now be done like this:

```java
LlamaIterator iterator = model.generate(params).iterator();
while (iterator.hasNext()) {
    iterator.next();
    if (Math.random() < 0.5) {
        iterator.cancel();
    }
}
```

Maven version `3.1.0` should soon be available.

**Comment by jrtp** [comment]
Awesome, thx for the quick inplementation. I just tried it, after the update the model loading interrupted with the previous llama.cpp I had compiled with GPU on windows, then after recompiling it *seemed* to work but for some reason inference suddenly stops in the middle. Any ideas what it could be?

            LlamaIterator iterator = model.generate(inferParams).iterator();
            while (iterator.hasNext()) {
                token = String.valueOf(iterator.next());
                Main.logLine(token);
                if (canceled) {
                    iterator.cancel();
                    break;
                }
            }

Same behaviour that inference just stops with the shipped llama.cpp (so no --Dde.kherud.llama.lib.path set) - just a lot slower ;)

**Comment by jrtp** [comment]
Weired, just switched back and forth between dependencies and now it just flies without obvious change - thx again!

**Comment by jrtp** [comment]
Ok, hopefully last question, now everything seems to work except exactly the same run.bat as previously throws this error now: Could not find or load main class .kherud.llama.lib.path=out
The cmd option used is this -Dde.kherud.llama.lib.path=out/
Without the option it works but without GPU, weiredly enough it also works with GPU started from intellij - any ideas how that could be affected? I triplechecked, with 3.0.2 this option was just working.

**Comment by jrtp** [comment]
FYI - user error - for some reason Intellij had 3.0.2 and 3.1.0 in the artifacts, didnt know this isnt updating automatically when changing maven deps

**Comment by kherud** [comment]
Great, glad to hear everything works now!
