### ISSUE TITLE
What's the model path in android?

### ISSUE THREAD

**Issue by Raffa064** [kherud/java-llama.cpp#69]
What type of path do it needs on setModelFilePath in android? Absolute, Asset relative, ... ?

**Comment by kherud** [comment]
Hey @samolego can you maybe answer this?

**Comment by samolego** [comment]
You need absolute path, make sure you have the permissions for external storage if you have it there.

**Comment by samolego** [comment]
Though llama.cpp now offers an official android example as well, you might want to look at there.

**Comment by Raffa064** [comment]
> Though llama.cpp now offers an official android example as well, you might want to look at there.

Where do I found it?

**Comment by samolego** [comment]
See https://github.com/ggerganov/llama.cpp/tree/master/examples/llama.android
